// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AssignPersonReducer from "../assign_person_reducer";
import CreateLaneReducer from "../create_lane_reducer";
import CreatePersonReducer from "../create_person_reducer";
import CreateTaskReducer from "../create_task_reducer";
import DeleteLaneReducer from "../delete_lane_reducer";
import DeletePersonReducer from "../delete_person_reducer";
import DeleteTaskReducer from "../delete_task_reducer";
import ImportPlanReducer from "../import_plan_reducer";
import MoveTaskReducer from "../move_task_reducer";
import MoveTaskToLaneReducer from "../move_task_to_lane_reducer";
import ReorderLaneReducer from "../reorder_lane_reducer";
import ResizeTaskReducer from "../resize_task_reducer";
import SetLaneColourReducer from "../set_lane_colour_reducer";
import SetTaskPercentReducer from "../set_task_percent_reducer";
import SetTaskPredecessorReducer from "../set_task_predecessor_reducer";
import UnassignPersonReducer from "../unassign_person_reducer";
import UpdateLaneReducer from "../update_lane_reducer";
import UpdatePersonReducer from "../update_person_reducer";
import UpdateTaskReducer from "../update_task_reducer";
import WipePlanReducer from "../wipe_plan_reducer";

export type AssignPersonParams = __Infer<typeof AssignPersonReducer>;
export type CreateLaneParams = __Infer<typeof CreateLaneReducer>;
export type CreatePersonParams = __Infer<typeof CreatePersonReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type DeleteLaneParams = __Infer<typeof DeleteLaneReducer>;
export type DeletePersonParams = __Infer<typeof DeletePersonReducer>;
export type DeleteTaskParams = __Infer<typeof DeleteTaskReducer>;
export type ImportPlanParams = __Infer<typeof ImportPlanReducer>;
export type MoveTaskParams = __Infer<typeof MoveTaskReducer>;
export type MoveTaskToLaneParams = __Infer<typeof MoveTaskToLaneReducer>;
export type ReorderLaneParams = __Infer<typeof ReorderLaneReducer>;
export type ResizeTaskParams = __Infer<typeof ResizeTaskReducer>;
export type SetLaneColourParams = __Infer<typeof SetLaneColourReducer>;
export type SetTaskPercentParams = __Infer<typeof SetTaskPercentReducer>;
export type SetTaskPredecessorParams = __Infer<typeof SetTaskPredecessorReducer>;
export type UnassignPersonParams = __Infer<typeof UnassignPersonReducer>;
export type UpdateLaneParams = __Infer<typeof UpdateLaneReducer>;
export type UpdatePersonParams = __Infer<typeof UpdatePersonReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;
export type WipePlanParams = __Infer<typeof WipePlanReducer>;

