// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PersonImport,
  LaneImport,
  TaskImport,
  AssignmentImport,
} from "./types";

export default {
  get people() {
    return __t.array(PersonImport);
  },
  get lanes() {
    return __t.array(LaneImport);
  },
  get tasks() {
    return __t.array(TaskImport);
  },
  get assignments() {
    return __t.array(AssignmentImport);
  },
};
