// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  laneId: __t.u64().name("lane_id"),
  name: __t.string(),
  startDay: __t.i32().name("start_day"),
  durationDays: __t.i32().name("duration_days"),
  percentComplete: __t.i32().name("percent_complete"),
  predecessorId: __t.u64().name("predecessor_id"),
});
