// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AppSecret = __t.object("AppSecret", {
  id: __t.u8(),
  passphrase: __t.string(),
});
export type AppSecret = __Infer<typeof AppSecret>;

export const Assignment = __t.object("Assignment", {
  id: __t.u64(),
  taskId: __t.u64(),
  personId: __t.u64(),
});
export type Assignment = __Infer<typeof Assignment>;

export const AssignmentImport = __t.object("AssignmentImport", {
  taskId: __t.u64(),
  personId: __t.u64(),
});
export type AssignmentImport = __Infer<typeof AssignmentImport>;

export const Authorized = __t.object("Authorized", {
  identity: __t.identity(),
});
export type Authorized = __Infer<typeof Authorized>;

export const Lane = __t.object("Lane", {
  id: __t.u64(),
  name: __t.string(),
  colour: __t.string(),
  sortOrder: __t.i32(),
});
export type Lane = __Infer<typeof Lane>;

export const LaneImport = __t.object("LaneImport", {
  id: __t.u64(),
  name: __t.string(),
  colour: __t.string(),
  sortOrder: __t.i32(),
});
export type LaneImport = __Infer<typeof LaneImport>;

export const Person = __t.object("Person", {
  id: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  avatarColour: __t.string(),
  initials: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const PersonImport = __t.object("PersonImport", {
  id: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  avatarColour: __t.string(),
  initials: __t.string(),
});
export type PersonImport = __Infer<typeof PersonImport>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  laneId: __t.u64(),
  name: __t.string(),
  startDay: __t.i32(),
  durationDays: __t.i32(),
  percentComplete: __t.i32(),
  predecessorId: __t.u64(),
});
export type Task = __Infer<typeof Task>;

export const TaskImport = __t.object("TaskImport", {
  id: __t.u64(),
  laneId: __t.u64(),
  name: __t.string(),
  startDay: __t.i32(),
  durationDays: __t.i32(),
  percentComplete: __t.i32(),
  predecessorId: __t.u64(),
});
export type TaskImport = __Infer<typeof TaskImport>;

