// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  taskId: __t.u64(),
  laneId: __t.u64(),
  name: __t.string(),
  startDay: __t.i32(),
  durationDays: __t.i32(),
  percentComplete: __t.i32(),
  predecessorId: __t.u64(),
};
